
###
http://localhost:4004/draft/BusinessPartners?$top=30
###
http://localhost:4004/draft/ControlKeys?$top=30
###
http://localhost:4004/draft/ServiceData?$top=30
###
http://localhost:4004/draft/TR_Currencies?$top=30


###
http://localhost:4004/draft/Airports
###
http://localhost:4004/draft/Airports(ID=2d1f3996-26a2-4cef-b4f5-c123a9126155,IsActiveEntity=true)
###
http://localhost:4004/draft/Airports(ID=2d1f3996-26a2-4cef-b4f5-c123a9126155,IsActiveEntity=true)/airport
###
http://localhost:4004/draft/Airports(ID=2d1f3996-26a2-4cef-b4f5-c123a9126155,IsActiveEntity=true)/plant

###
http://localhost:4004/draft/Airports(ID=2d1f3996-26a2-4cef-b4f5-c123a9126155,IsActiveEntity=true)?$select=ID&$expand=plant
###
http://localhost:4004/draft/Airports(ID=2d1f3996-26a2-4cef-b4f5-c123a9126155,IsActiveEntity=true)?$select=ID&$expand=airport
###
http://localhost:4004/draft/Airports?$select=ID&$expand=plant
###
http://localhost:4004/draft/Airports?$select=ID&$expand=airport
###
http://localhost:4004/draft/Airports?$select=ID&$expand=airport($select=ID,aptcd_icao,name)
###
http://localhost:4004/draft/Airports?$select=ID&$expand=plant($select=ID,Name)
###
http://localhost:4004/draft/Airports?$select=ID&$expand=airport,plant
###
http://localhost:4004/draft/Airports(ID=171c200f-facc-4e57-9a3d-67826ae7b8f3,IsActiveEntity=true)?$select=ID&$expand=airport,plant
###
http://localhost:4004/draft/Airports(ID=171c200f-facc-4e57-9a3d-67826ae7b8f3,IsActiveEntity=true)?$select=ID&$expand=airport($select=ID,aptcd_icao,name),plant($select=ID,Name)


###
http://localhost:4004/draft/Carriers
###
http://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)
###
http://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)/carrier
###
http://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)/orderType
###
http://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)/plant
###
http://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)/companyCode
###
http://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)/mainWorkCenter
###
http://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)/controlKey
###
http://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)/purchaseOrganization
###
http://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)/materialGroup
###
http://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)/awbOrderType





###
http://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)?$select=ID&$expand=plant
###
http://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)?$select=ID&$expand=plant,carrier,orderType,companyCode,controlKey,awbOrderType,materialGroup,purchaseOrganization,mainWorkCenter
###
http://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)?$select=ID&$expand=plant($select=ID),carrier($select=ID),orderType($select=ID),companyCode($select=ID),controlKey($select=ID),awbOrderType($select=ID),materialGroup($select=ID),purchaseOrganization($select=ID),mainWorkCenter($select=ID)












###
http://localhost:4004/draft/PurHeader
###
http://localhost:4004/draft/PurHeader(ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true)
###
http://localhost:4004/draft/PurHeader(ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true)/airport
###
http://localhost:4004/draft/PurHeader(ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true)/carrier
###
http://localhost:4004/draft/PurHeader(ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true)/purchaseOrganization
###
http://localhost:4004/draft/PurHeader(ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true)/vendor
###
http://localhost:4004/draft/PurHeader(ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true)/items




###
http://localhost:4004/draft/PurHeader(ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true)?$select=ID&$expand=airport
###
http://localhost:4004/draft/PurHeader(ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true)?$select=ID&$expand=carrier
###
http://localhost:4004/draft/PurHeader(ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true)?$select=ID&$expand=purchaseOrganization
###
http://localhost:4004/draft/PurHeader(ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true)?$select=ID&$expand=vendor
###
http://localhost:4004/draft/PurHeader(ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true)?$select=ID&$expand=items
###
http://localhost:4004/draft/PurHeader(ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true)?$select=ID&$expand=airport,carrier,purchaseOrganization,vendor,items
###
http://localhost:4004/draft/PurHeader(ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true)?$select=ID&$expand=airport($select=ID),carrier($select=ID),purchaseOrganization($select=ID),vendor($select=ID),items($select=ID)









###
http://localhost:4004/draft/PurItems

###
http://localhost:4004/draft/PurItems(purHeader_ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true,ID='00020')

###
http://localhost:4004/draft/PurItems(purHeader_ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true,ID='00010')/status

###
http://localhost:4004/draft/PurItems(purHeader_ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true,ID='00010')/serviceNumber
###
http://localhost:4004/draft/PurItems(purHeader_ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true,ID='00010')/vendor
###
http://localhost:4004/draft/PurItems(purHeader_ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true,ID='00010')/carrier
###
http://localhost:4004/draft/PurItems(purHeader_ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true,ID='00010')/currency
###
http://localhost:4004/draft/PurItems(purHeader_ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true,ID='00020')/brf_id





###
http://localhost:4004/draft/PurItems(purHeader_ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true,ID='00010')?$select=ID&$expand=serviceNumber
###
http://localhost:4004/draft/PurItems(purHeader_ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true,ID='00010')?$select=ID&$expand=vendor
###
http://localhost:4004/draft/PurItems(purHeader_ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true,ID='00010')?$select=ID&$expand=carrier
###
http://localhost:4004/draft/PurItems(purHeader_ID=08cda5d5-e570-476b-8a23-4f5a59a25c03,IsActiveEntity=true,ID='00010')?$select=ID&$expand=currency