###
http://localhost:4004/draft/Airports(ID=2d1f3996-26a2-4cef-b4f5-c123a9126155,IsActiveEntity=true)
###
http://localhost:4004/draft/Airports(ID=2d1f3996-26a2-4cef-b4f5-c123a9126155,IsActiveEntity=true)/airport
###
http://localhost:4004/draft/Airports(ID=2d1f3996-26a2-4cef-b4f5-c123a9126155,IsActiveEntity=true)/plant



###
http://localhost:4004/browse/Airports(ID=2d1f3996-26a2-4cef-b4f5-c123a9126155)
###
http://localhost:4004/browse/Airports(ID=2d1f3996-26a2-4cef-b4f5-c123a9126155)/airport
###
http://localhost:4004/browse/Airports(ID=2d1f3996-26a2-4cef-b4f5-c123a9126155)/plant





###
http://localhost:4004/draft/Airports?$expand=plant
###
http://localhost:4004/draft/Airports?$expand=airport
###
http://localhost:4004/draft/Airports?$expand=airport,plant


###
http://localhost:4004/browse/Airports?$expand=plant
###
http://localhost:4004/browse/Airports?$expand=airport
###
http://localhost:4004/browse/Airports?$expand=airport,plant




###
http://localhost:4004/browse/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002)
###
http://localhost:4004/browse/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002)/carrier
###
http://localhost:4004/browse/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002)/plant
###
http://localhost:4004/browse/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002)/companyCode
###
http://localhost:4004/browse/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002)/controlKey
###
http://localhost:4004/browse/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002)/orderType




###
http://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)
###
http://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)/carrier
###
http://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)/plant
###
http://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)/companyCode
###
http://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)/controlKey
###
http://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)/orderType

###
http://localhost:4004/draft/Carriers?$expand=plant
###
http://localhost:4004/draft/Carriers?$expand=orderType
###
http://localhost:4004/draft/Carriers?$expand=carrier
###
http://localhost:4004/draft/Carriers?$expand=companyCode
###
http://localhost:4004/draft/Carriers?$expand=controlKey