###
http://localhost:4004/draft/Airports(ID=2d1f3996-26a2-4cef-b4f5-c123a9126155,IsActiveEntity=true)/airport
###
https://localhost:4004/draft/Airports(ID=2d1f3996-26a2-4cef-b4f5-c123a9126155,IsActiveEntity=true)/plant
###
http://localhost:4004/draft/Airports(ID=2d1f3996-26a2-4cef-b4f5-c123a9126155,IsActiveEntity=true)
###
http://localhost:4004/draft/Airports?$expand=plant
###
http://localhost:4004/draft/Airports?$expand=airport
###
http://localhost:4004/draft/Airports?$expand=airport,plant



###
http://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)/carrier
###
https://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)/plant
###
https://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)/companyCode
###
https://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)/controlKey
###
https://localhost:4004/draft/Carriers(ID=915de690-55f6-11ec-bf63-0242ac130002,IsActiveEntity=true)/orderType

###
http://localhost:4004/draft/Carriers?$expand=plant
###
http://localhost:4004/draft/Carriers?$expand=orderType
###
http://localhost:4004/draft/Carriers?$expand=carrier
###
http://localhost:4004/draft/Carriers?$expand=companyCode
###
http://localhost:4004/draft/Carriers?$expand=controlKey